@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":EditFoodEntryCommand": execute()
activate ":EditFoodEntryCommand"
alt Food does not exist in database

    create ":Food"
    ":EditFoodEntryCommand" -> ":Food" : new
    activate ":Food"
    return customFood:Food

    ":EditFoodEntryCommand" -> ":EntryDatabase" : editEntryAtIndex
    activate ":EntryDatabase"
    return

    ":EditFoodEntryCommand" -> ":FoodDatabase" : addFood
    activate ":FoodDatabase"
    return

else Food exists in database

    ":EditFoodEntryCommand" -> ":EntryDatabase" : editEntryAtIndex
    activate ":EntryDatabase"
    return

end
return output

@enduml
