@startuml
'https://plantuml.com/class-diagram

autonumber

-> ":ViewSuggestionsCommand": execute(entryDatabase, foodDatabase, mealPlanDatabase, user)
activate ":ViewSuggestionsCommand"

":ViewSuggestionsCommand" -> ":User" : getCalorieGoal()
activate ":User"
return calorieGoal

":ViewSuggestionsCommand" -> ":EntryDatabase" : getTotalDailyCalorie()
activate ":EntryDatabase"
return caloriesConsumed

":ViewSuggestionsCommand" -> ":FoodDatabase" : findSuggestions(type, remaining, isSort)
note right
remaining = calorieGoal - caloriesConsumed
end note
activate ":FoodDatabase"
return suggestions

":ViewSuggestionsCommand" -> ":Ui" : printMatchingSuggestions(suggestions)
activate ":Ui"
return

return
@enduml