package fitnus.utility;

import fitnus.database.EntryDatabase;
import fitnus.database.FoodDatabase;
import fitnus.database.MealPlanDatabase;
import fitnus.tracker.Entry;
import fitnus.tracker.Food;

import java.io.InputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Scanner;

/**
 * Handles interactions with the user.
 */
public class Ui {
    //private final Scanner sc = new Scanner(System.in);

    public static final String DIVIDER = "------------------\n";
    public static final String INIT_GENDER = "[X] Please enter your gender (m/f):";
    public static final String INIT_AGE = "[X] Please enter your age in years:";
    public static final String INIT_HEIGHT = "[X] Please enter your height in cm:";
    public static final String INIT_WEIGHT = "[X] Please enter your weight in kg:";
    public static final String INIT_SUCCESS = "Generated your daily calorie needs accordingly.";
    public static final String USER_INPUT = "You: ";
    public static final String WELCOME_MESSAGE = DIVIDER
            + "Welcome to FitNUS Tracker!";

    /**
     * Prints a welcome message.
     */
    public static void printWelcomeMessage() {
        println(WELCOME_MESSAGE);
    }

    /**
     * Prints a message to the user with a new line.
     *
     * @param message The message to be printed.
     */
    public static void println(String message) {
        System.out.println(message);
    }

    /**
     * Prints a message to the user.
     *
     * @param message The message to be printed.
     */
    public static void print(String message) {
        System.out.print(message);
    }

    /**
     * Prints a message informing the user that there were some problems
     * when preloading the database data.
     */
    public static void printPreloadDatabaseError() {
        System.out.println("Error encountered while preloading database :("
                + " some data may have been lost");
    }

    /**
     * Prints a message informing the user that there were some problems
     * when preloading the user data.
     */
    public static void printPreloadUserError() {
        System.out.println("Error encountered while preloading user data :(");
    }

    /**
     * Prints a message informing the user that there were some problems
     * when preloading the weight data.
     */
    public static void printPreloadWeightError() {
        System.out.println("Error encountered while preloading weight data :(");
    }

    /**
     * Reads the user's inputs.
     *
     * @return The user's inputs as a String.
     */
    public String readInput(InputStream in, PrintStream out) {
        Scanner sc = new Scanner(in);
        String userInput = "";
        do {
            userInput = sc.nextLine().toLowerCase().trim();
            if (userInput.equals("")) {
                out.println("Input cannot be empty! Please try again");
            }
        } while (userInput.equals(""));
        assert !userInput.trim().equals("") : "input cannot be empty";
        return userInput;
    }

    public String[] readIndexesInput(InputStream in, PrintStream out) {
        Scanner sc = new Scanner(in);
        String userInput = "";
        do {
            userInput = sc.nextLine().toLowerCase().trim();
            if (userInput.equals("")) {
                out.println("Input cannot be empty! Please try again");
            }
        } while (userInput.equals(""));
        assert !userInput.trim().equals("") : "input cannot be empty";
        return userInput.split(" ");
    }

    /**
     * Prints information regarding MealPlan creation.
     *
     * @param fd FoodDatabase object.
     */
    public static void printMealPlanCreation(FoodDatabase fd) {
        System.out.println("We will now create a mealplan! To create a Meal plan, "
                + "enter the indexes of the foods below with spaces in between each index.");
        System.out.println("For example: 1 2 8 4");
        System.out.println("Indexes that are not present/invalid will be ignored. "
                + "Duplicates are allowed, but try to not eat so much food :)");
        System.out.println("Here is a list of all foods present in the database:");
        System.out.println(fd.listFoods());
    }

    public static void printAutoAddedFoodCategory(String mealType, boolean isAutoGenerated) {
        if (isAutoGenerated) {
            System.out.println("Food category not detected. Based on current timing, "
                    + "the following category has been added: " + mealType);
        } else {
            System.out.println("The following food category has been tagged: " + mealType);
        }
    }

    /**
     * Prints to the user the content of the matchingFoods ArrayList.
     *
     * @param matchingFoods The ArrayList containing matching Food objects.
     */
    public static void printMatchingFoods(ArrayList<Food> matchingFoods) {
        for (int i = 1; i <= matchingFoods.size(); i++) {
            System.out.println(" " + i + "."
                    + matchingFoods.get(i - 1).toString());
        }
    }

    public static void printPromptUserFoodInput(String foodName) {
        System.out.println("Oops! \"" + foodName + "\" does not exist in the database!");
        Ui.print(Ui.DIVIDER);
    }

    public static void printOutOfRangeInputInteger(int num) {
        System.out.println("Input " + num + " was out of range. Ignoring Input");
    }

    public static void printInvalidInputInteger(String input) {
        System.out.println("Input " + input + " was not an integer. Ignoring input.");
    }

    public static void printAddCalorieToFood(String foodName) {
        System.out.println("Adding \"" + foodName + "\"...");
        System.out.println("[X] Enter calories of \"" + foodName + "\":");
        Ui.print(Ui.USER_INPUT);
    }

    /**
     * Prints to the user the content of the matchingEntries ArrayList.
     *
     * @param matchingEntries ArrayList containing matching Entry objects.
     */
    public static void printMatchingEntries(ArrayList<Entry> matchingEntries) {
        if (matchingEntries.size() == 0) {
            return;
        }
        System.out.println("Here are the matching entries in your database:");
        for (int i = 1; i <= matchingEntries.size(); i++) {
            System.out.println(" " + i + "."
                    + matchingEntries.get(i - 1).toString());
        }
    }

    /**
     * Prints the calorie goal.
     *
     * @param calorieGoal The calorie goal value.
     */
    public static void printCalorieGoal(int calorieGoal) {
        println("Your daily calorie goal is " + calorieGoal + "kcal.");
    }

}
