@startuml
'https://plantuml.com/sequence-diagram

-> ":EntryDatabase": convertDatabaseToString()
activate ":EntryDatabase"

loop For every FoodTracker object in EntryDatabase

    ":EntryDatabase" -> ":Entry": getFood()
    activate ":Entry"
    return food

    ":EntryDatabase" -> ":Entry": getDate()
    activate ":Entry"
    return date

    ":EntryDatabase" -> ":Food": getName()
    activate ":Food"
    return name

    ":EntryDatabase" -> ":Food": getCalories()
    activate ":Food"
    return calories

    ":EntryDatabase" -> ":Food": getType()
    activate ":Food"
    return type

    ":EntryDatabase" -> ":EntryDatabase": append info onto String
    
end

return String
@enduml
