@startuml
'https://plantuml.com/sequence-diagram

-> ":EntryDatabase": preloadDatabase(reader)
activate ":EntryDatabase"
participant Parser << Class >>
loop While there are still unread lines

    ":EntryDatabase" -> Parser: parseMealType(input, isDatabaseRequest)
    activate Parser
    return mealType

    ":EntryDatabase" -> Parser: parseFoodType(type)
    activate Parser
    return type

    ":EntryDatabase" -> Parser: getDate()
    activate Parser
    return date

    create ":Food"
    ":EntryDatabase" -> ":Food": new Food(name, calories, type)
    activate ":Food"
    return food

    create ":Entry"
    ":EntryDatabase" -> ":Entry": new Entry(mealType, food, date)
    activate ":Entry"
    return entry

    ":EntryDatabase" -> ":EntryDatabase": addEntry(entry)
    activate ":EntryDatabase"
    return

end

return
@enduml
