@startuml
'https://plantuml.com/sequence-diagram


-> ":FoodDatabase": preloadDatabase()
participant Parser << Class >>
activate ":FoodDatabase"

loop While there are still unread lines

    ":FoodDatabase" -> Parser: parseFoodType()
    activate Parser
    return type

    ":FoodDatabase" -> ":FoodDatabase": addFood(name, calories, type)
    activate ":FoodDatabase"
    return


end

return
@enduml
