@startuml
'https://plantuml.com/sequence-diagram

-> ":FoodDatabase": preloadDatabase()
activate ":FoodDatabase"

loop While there are still unread lines

    ":FoodDatabase" -> "<<Class>>\nParser": parseFoodType()
    activate "<<Class>>\nParser"
    return type

    ":FoodDatabase" -> ":FoodDatabase": addFood(name, calories, type)
    activate ":FoodDatabase"
    return


end

return
@enduml