@startuml
'https://plantuml.com/sequence-diagram

-> ":FoodDatabase": convertDatabaseToString()
activate ":FoodDatabase"

loop For every Food object in FoodDatabase

    ":FoodDatabase" -> ":Food": getName()
    activate ":Food"
    return name

    ":FoodDatabase" -> ":Food": getCalories()
    activate ":Food"
    return calories

    ":FoodDatabase" -> ":Food": getType()
    activate ":Food"
    return type

end

return content as String
@enduml
