@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":ListFoodEntryAllCommand": execute()
activate ":ListFoodEntryAllCommand"

    ":ListFoodEntryAllCommand" -> ":EntryDatabase" : listEntries
    activate ":EntryDatabase"
    return entries

return output

@enduml
