@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> ":ListFoodEntryCustomCommand": execute()
activate ":ListFoodEntryCustomCommand"

    create ":EntryDatabase"
    ":ListFoodEntryCustomCommand" -> ":EntryDatabase" : getPastDaysEntryDatabase(int)
    activate ":EntryDatabase"
    return CustomDayEntryDatabase: EntryDatabase
    ":ListFoodEntryCustomCommand" -> ":EntryDatabase" : listEntries
    activate ":EntryDatabase"
    return entries

return output

@enduml
