@startuml
'https://plantuml.com/sequence-diagram

-> ":ListFoodEntryAllCommand": execute(ed, fd, md, us)
activate ":ListFoodEntryAllCommand"

    ":ListFoodEntryAllCommand" -> ":EntryDatabase" : listEntries()
    activate ":EntryDatabase"
    return entries

return output

@enduml
