@startuml
'https://plantuml.com/sequence-diagram

-> ":ListFoodEntryCustomCommand": execute(ed, fd, md, us)
activate ":ListFoodEntryCustomCommand"

    create ":EntryDatabase"
    ":ListFoodEntryCustomCommand" -> ":EntryDatabase" : getPastDaysEntryDatabase(days)
    activate ":EntryDatabase"
    return CustomDayEntryDatabase
    ":ListFoodEntryCustomCommand" -> ":EntryDatabase" : listEntries()
    activate ":EntryDatabase"
    return entries

return output

@enduml
