@startuml
'https://plantuml.com/sequence-diagram

activate ":FitNUS"
":FitNUS" -> "<<class>>\n Storage": saveFoodDatabase(foodDatabase)
activate "<<class>>\n Storage"
"<<class>>\n Storage" -> ":FoodDatabase" : convertDatabaseToString()
activate ":FoodDatabase"
loop for all food objects
":FoodDatabase" -> ":Food" : getName()
activate ":Food"
return name
":FoodDatabase" -> ":Food" : getCalories()
activate ":Food"
return calories
":FoodDatabase" -> ":Food" : getType()
activate ":Food"
return type
end
return content as String
"<<class>>\n Storage" -> "<<class>>\n Storage" : saveData(filePath, content)
activate "<<class>>\n Storage"
return
return


@enduml