@startuml
'https://plantuml.com/sequence-diagram
activate ":FitNUS"
":FitNUS" -> "<<class>>\n Storage": initialiseFoodDatabase()
activate "<<class>>\n Storage"

"<<class>>\n Storage" -> ":FoodDatabase": preloadDatabase()
activate ":FoodDatabase"

loop While there are still unread lines
    ":FoodDatabase" -> ":FoodDatabase": loadFood()
    activate ":FoodDatabase"

    ":FoodDatabase" -> "<<Class>>\nParser": parseFoodType()
    activate "<<Class>>\nParser"
    return type

    ":FoodDatabase" -> ":FoodDatabase": addFood(name, calories, type)
    activate ":FoodDatabase"
    return

    return
end
return

return
@enduml