@startuml
'https://plantuml.com/sequence-diagram
activate ":FitNUS"
":FitNUS" -> "<<class>>\n Storage": initialiseFoodDatabase(database)
activate "<<class>>\n Storage"

"<<class>>\n Storage" -> ":FoodDatabase": preloadDatabase(reader)
activate ":FoodDatabase"

loop While there are still unread lines
    ":FoodDatabase" -> ":FoodDatabase": loadFood(line)
    activate ":FoodDatabase"

    ":FoodDatabase" -> "<<Class>>\nParser": parseFoodType(type)
    activate "<<Class>>\nParser"
    return foodType

    ":FoodDatabase" -> ":FoodDatabase": addFood(name, calories, foodType)
    activate ":FoodDatabase"
    create ":Food"
    ":FoodDatabase" -> ":Food": new Food(name, calories, foodType)
    activate ":Food"
    return food

    return

    return
end
return

return
@enduml