@startuml
'https://plantuml.com/sequence-diagram

activate ":FitNUS"
":FitNUS" -> "<<class>>\n Storage": saveFoodDatabase(database)
activate "<<class>>\n Storage"
"<<class>>\n Storage" -> ":FoodDatabase" : convertDatabaseToString()
activate ":FoodDatabase"
loop for all food objects
    ":FoodDatabase" -> ":Food": convertToStringForStorage()
    activate ":Food"
    ":Food" -> ":Food": getName()
    activate ":Food"
    return name
    ":Food" -> ":Food": getCalories()
    activate ":Food"
    return calories
    ":Food" -> ":Food": getType()
    activate ":Food"
    return type
    return Food object as String
end
return content as String
"<<class>>\n Storage" -> "<<class>>\n Storage" : saveData(filePath, content)
activate "<<class>>\n Storage"
return
return


@enduml